config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :event, only: [ :index, :new, :create, :show ] do
    member do
      post "join", to: "attendance#create"
      delete "leave", to: "attendance#delete"
      delete "delete", to: "event#delete"
    end
  end
  resources :user, only: :show

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "event#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: "author_id"

  has_many :attendances, dependent: :destroy
  has_many :attendants, through: :attendances, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Indixakile lendawo
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, foreign_key: "author_id"
  has_many :attendances, dependent: :destroy
  has_many :attended_events, through: :attendances, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/attendance_cotroller.rb
class AttendanceController < ApplicationController
  def create
    @attendance = Attendance.new(event: Event.find_by(id: params[:id]), user: current_user)
    if @attendance.save
      redirect_to @attendance.event, notice: "You have been added"
    else
      redirect_to @attendance.event, alert: "Failed to join the event!"
    end
  end

  def delete
    @attendance = Attendance.find_by(event: Event.find_by(id: params[:id]), user: current_user)
    if @attendance.delete
      redirect_to @attendance.event, notice: "You're out!"
    else
      redirect_to @attendance.event, alert: "Failed to leave!"
    end
  end
end

app/controllers/events_controller.rb
class EventController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create ]
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to event_index_path
    else
      puts @event.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @event = Event.find_by(id: params[:id])
  end

  def delete
    @event = Event.find_by(id: params[:id])
    if current_user == @event.author && @event.delete
      redirect_to event_index_path
    else
      puts @event.errors.full_messages
      render :show, status: :unprocessable_entity
    end
  end
  private

  def event_params
    params.expect(event: [ :title, :date, :place ])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_events.html.erb
<ol>
    <% @events.each do |event| %>
        <li class="event">
            <h1><%= link_to event.title, event_path(event) %></h1>
            <h3>Date: <%= event.date %></h3>
            <h3>Place: <%= event.place %></h3>
            <h3>Author: <%= link_to event.author.email, user_path(event.author.id) %></h3>
            <h5>Attendants:
                <% event.attendants.each_with_index do |user, i| %>
                    <% if i > 0 %>, <% end %>
                    <%= user.email %>
                <% end %>
                <% if event.attendants.empty? %> None <% end %>
            </h5>
        </li>
    <% end %>
    <% if @events.empty? %> <h3>None</h3> <% end %>
</ol>

app/views/events/index.html.erb
<%= render "events", events: @events %>

app/views/events/new.html.erb
<%= form_with url: "/event", model: @event do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :date %>
        <%= form.date_field :date %>
    </div>
    <div>
        <%= form.label :place %>
        <%= form.text_field :place %>
    </div>
    <%= form.submit %>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>
<h3>Date: <%= @event.date %></h3>
<h3>Place: <%= @event.place %></h3>
<h3>Author: <%= link_to @event.author.email, user_path(@event.author.id) %></h3>
<h5>Attendants:
    <% @event.attendants.each_with_index do |user, i| %>
        <% if i > 0 %>, <% end %>
        <%= user.email %>
    <% end %>
    <% if @event.attendants.empty? %> None <% end %>
</h5>
<% if user_signed_in? && @event.author != current_user %>
    <% unless @event.attendants.include?(current_user) %>
        <%= button_to "Join", join_event_path(@event), method: :post %>
    <% else %>
        <%= button_to "Leave", leave_event_path(@event), method: :delete %>
    <% end %>
<% end %>
<% if @event.author == current_user %>
    <%= button_to "REMOVE", delete_event_path(@event), method: :delete %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Private Events" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'rails-ujs' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= link_to "Home", root_path %>
      <% if user_signed_in? %>
        <%= link_to "New Event", new_event_path %>
        <div class="divider"></div>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% else %>
        <div class="divider"></div>
        <%= link_to "Sign In", new_user_session_path %>
        <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/user/show.html.erb
<h1><%= @user.email %>'s Events!</h1>
<% @events = @user.events %>
<%= render "event/events", events: @events %>
<h1><%= @user.email %> is attending</h1>
<% @events = @user.attended_events %>
<%= render "event/events", event: @events %>